### ISSUE TITLE
`yarn run dev` Error

### ISSUE THREAD

**Issue by nixwl** [DaanDeMeyer/h2vis#37]
I hav successful build h2vis（use yarn），but I can't run `yarn run dev`  
![image](https://github.com/DaanDeMeyer/h2vis/assets/80773211/c1e47fed-679d-4aec-82c2-4113ecff187c)

Is webpack-cli needed ? which version should I use ?

**Comment by nixwl** [comment]
This is use yarn 1.22， but they ar same：
```
nixwl@nixwl:~/h2vis$ yarn run dev
yarn run v1.22.21
$ webpack-dev-server --config webpack.website.js
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
module.js:487
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nixwl/h2vis/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
